# Generated by Django 5.2.10 on 2026-02-05 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('externaldata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoVencido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO_PRE', models.CharField(max_length=20, verbose_name='Código Establecimiento')),
                ('CODIGO_MED', models.CharField(max_length=20, verbose_name='Código Medicamento')),
                ('MEDLOTE', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('MEDFECHVTO', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('SALDO', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Actual')),
                ('severidad', models.CharField(choices=[('vencido', 'Vencido'), ('por_vencer', 'Por Vencer (30 días)'), ('alerta', 'Alerta (60 días)')], max_length=20)),
                ('dias_restantes', models.IntegerField(verbose_name='Días Restantes para Vencimiento')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('registro_formdet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimientos_detectados', to='externaldata.formdet')),
                ('usuario_deteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vencimientos_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicamento Vencido',
                'verbose_name_plural': 'Medicamentos Vencidos',
                'ordering': ['MEDFECHVTO', 'severidad'],
                'indexes': [models.Index(fields=['MEDFECHVTO'], name='vencimiento_MEDFECH_9b05a6_idx'), models.Index(fields=['severidad'], name='vencimiento_severid_db49b4_idx'), models.Index(fields=['CODIGO_PRE'], name='vencimiento_CODIGO__0735ba_idx'), models.Index(fields=['resuelto'], name='vencimiento_resuelt_e98343_idx')],
            },
        ),
    ]
