# Generated by Django 5.2.10 on 2026-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentovencido',
            name='ANNOMES',
            field=models.CharField(blank=True, help_text='Formato: AAAAMM (ej: 202501)', max_length=6, null=True, verbose_name='Mes/Año'),
        ),
    ]
