# Generated by Django 5.2.10 on 2026-02-10 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externaldata', '0001_initial'),
        ('vencimientos', '0002_medicamentovencido_annomes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamentovencido',
            options={'ordering': ['FEC_EXP', 'severidad'], 'verbose_name': 'Medicamento Vencido', 'verbose_name_plural': 'Medicamentos Vencidos'},
        ),
        migrations.RemoveIndex(
            model_name='medicamentovencido',
            name='vencimiento_MEDFECH_9b05a6_idx',
        ),
        migrations.RenameField(
            model_name='medicamentovencido',
            old_name='MEDFECHVTO',
            new_name='FEC_EXP',
        ),
        migrations.AddIndex(
            model_name='medicamentovencido',
            index=models.Index(fields=['FEC_EXP'], name='vencimiento_FEC_EXP_57e621_idx'),
        ),
    ]
