# Generated by Django 5.2.10 on 2026-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesamientoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=50)),
                ('total_registros', models.IntegerField()),
                ('guardados', models.IntegerField()),
                ('columnas', models.TextField()),
                ('tablas_guardadas', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
