# Generated by Django 5.2.10 on 2026-02-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('externaldata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('total_registros_analizados', models.IntegerField(default=0)),
                ('total_inconsistencias', models.IntegerField(default=0)),
                ('total_inconsistencias_stock_saldo', models.IntegerField(default=0)),
                ('tiempo_inicio', models.DateTimeField()),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('resumen_codigo_pre', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Verificación',
                'verbose_name_plural': 'Estadísticas de Verificación',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='InconsistenciaFormDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_saldo', 'Inconsistencia Stock-Saldo')], default='stock_saldo', max_length=50)),
                ('CODIGO_PRE', models.CharField(db_index=True, max_length=11)),
                ('CODIGO_MED', models.CharField(db_index=True, max_length=7)),
                ('ANNOMES_actual', models.CharField(db_index=True, max_length=6)),
                ('ANNOMES_anterior', models.CharField(blank=True, max_length=6, null=True)),
                ('SALDO_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('STOCKFIN_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('descripcion', models.TextField(blank=True)),
                ('severidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('datos_contexto', models.JSONField(blank=True, null=True)),
                ('archivo_procesado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencias', to='externaldata.archivosprocesados')),
                ('usuario_deteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inconsistencia FormDet',
                'verbose_name_plural': 'Inconsistencias FormDet',
                'ordering': ['-fecha_deteccion', 'severidad'],
                'indexes': [models.Index(fields=['CODIGO_PRE', 'ANNOMES_actual'], name='verificacio_CODIGO__e02d8c_idx'), models.Index(fields=['tipo', 'resuelta'], name='verificacio_tipo_ce7944_idx'), models.Index(fields=['fecha_deteccion'], name='verificacio_fecha_d_5af16b_idx')],
            },
        ),
    ]
