# Generated by Django 5.2.10 on 2026-02-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDLOTE_actual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDLOTE_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
