# Generated by Django 5.2.10 on 2026-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0002_inconsistenciaformdet_medlote_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='FFINAN_actual',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='FFINAN_anterior',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDFECHVTO_actual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDFECHVTO_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDREGSAN_actual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDREGSAN_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_actual',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_anterior',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
