# Generated by Django 5.2.10 on 2026-02-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0003_inconsistenciaformdet_ffinan_actual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='FFINAN_actual',
            new_name='FFINAN',
        ),
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='MEDFECHVTO_actual',
            new_name='MEDFECHVTO',
        ),
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='MEDLOTE_actual',
            new_name='MEDLOTE',
        ),
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='MEDLOTE_anterior',
            new_name='MEDREGSAN',
        ),
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='TIPSUM_actual',
            new_name='TIPSUM',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='FFINAN_anterior',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='MEDFECHVTO_anterior',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='MEDREGSAN_actual',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='MEDREGSAN_anterior',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='SALDO_actual',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='STOCKFIN_anterior',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_anterior',
        ),
    ]
