# Generated by Django 5.2.10 on 2026-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0004_rename_ffinan_actual_inconsistenciaformdet_ffinan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='FFINAN_actual',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='FFINAN_anterior',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDFECHVTO_actual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDFECHVTO_anterior',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDLOTE_actual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDLOTE_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDREGSAN_actual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='MEDREGSAN_anterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='SALDO_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='STOCKFIN_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_actual',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_anterior',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
