# Generated by Django 5.2.10 on 2026-02-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0005_inconsistenciaformdet_ffinan_actual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='TIPSUM',
            new_name='TIPSUM2',
        ),
    ]
