# Generated by Django 5.2.10 on 2026-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0006_rename_tipsum_inconsistenciaformdet_tipsum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inconsistenciaformdet',
            name='TIPSUM2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_actual',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='inconsistenciaformdet',
            name='TIPSUM_anterior',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
