# Generated by Django 5.2.10 on 2026-02-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificaciones', '0007_alter_inconsistenciaformdet_tipsum2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='MEDFECHVTO',
            new_name='FEC_EXP',
        ),
        migrations.RenameField(
            model_name='inconsistenciaformdet',
            old_name='MEDFECHVTO_actual',
            new_name='FEC_EXP_actual',
        ),
        migrations.RemoveField(
            model_name='inconsistenciaformdet',
            name='MEDFECHVTO_anterior',
        ),
        migrations.AddField(
            model_name='inconsistenciaformdet',
            name='FEC_EXP_anterior',
            field=models.DateField(blank=True, null=True),
        ),
    ]
