# Generated by Django 5.2.10 on 2026-02-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verificaciones', '0007_alter_inconsistenciaformdet_tipsum2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionDBF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_original', models.CharField(max_length=255)),
                ('ruta_archivo_original', models.TextField()),
                ('nombre_archivo_corregido', models.CharField(blank=True, max_length=255)),
                ('ruta_archivo_corregido', models.TextField(blank=True)),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('corregido', 'Corregido'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_corregido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observaciones', models.TextField(blank=True)),
                ('inconsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='verificaciones.inconsistenciaformdet')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corrección DBF',
                'verbose_name_plural': 'Correcciones DBF',
                'ordering': ['-fecha_correccion'],
            },
        ),
    ]
