# Generated by Django 5.2.10 on 2026-02-06 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('vaciar', 'Vaciar Tabla'), ('eliminar', 'Eliminar Registros Filtrados'), ('backup', 'Crear Backup'), ('restaurar', 'Restaurar Backup'), ('optimizar', 'Optimizar Tabla')], max_length=20)),
                ('tabla', models.CharField(max_length=100)),
                ('filtros', models.JSONField(blank=True, null=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_eliminados', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación de Limpieza',
                'verbose_name_plural': 'Operaciones de Limpieza',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
